@startuml
abstract class AbstractClass {
    +templateMethod()
    -primitiveOperation1()
    -primitiveOperation2()
}

class ConcreteClassA {
    +primitiveOperation1()
    +primitiveOperation2()
}

class ConcreteClassB {
    +primitiveOperation1()
    +primitiveOperation2()
}

AbstractClass <|-- ConcreteClassA
AbstractClass <|-- ConcreteClassB
@enduml