@startuml
class FireSpellNoTemplate {
    +prepareSpell()
    +chooseSpell()
    +gatherIngredients(spell)
    +castSpell(spell)
}

class InvisibilitySpellNoTemplate {
    +prepareSpell()
    +chooseSpell()
    +gatherIngredients(spell)
    +castSpell(spell)
}

class MageKoboldNoTemplate {
    -spellCastingMethod
    +prepareSpell()
    +changespellCastingMethod(spellCastingMethod)
    +main(args: String[])
}

MageKoboldNoTemplate --> FireSpellNoTemplate
MageKoboldNoTemplate --> InvisibilitySpellNoTemplate
@enduml