@startuml

skinparam line ortho

class DiminuirVolume {
    - private tocador: Tocador;
    - private nivel : int;

    + DiminuirVolume(tocador: Tocador, nivel: int);
    + executar(tocador : Tocador): String;
}

@enduml