@startuml
skinparam linetype ortho


abstract class Component {
  + {abstract} operation(): void
}
class ConcreteComponent extends Component { 
  + operation(): void
}
class Decorator extends Component{
  - component: Component
  + operation(): void
}

class ConcreteDecoratorA extends Decorator {
  + operation(): void
  + addedState: string
}
class ConcreteDecoratorB extends Decorator {
  + operation(): void
  + addedBehavior(): void
}

Decorator o-> Component
ConcreteComponent -[hidden] Decorator
ConcreteDecoratorA -[hidden] ConcreteDecoratorB

note right of Decorator::component
  component.operation()
end note

note right of ConcreteDecoratorB::operation
  addedBehavior()
end note

@enduml
