@startuml
abstract class Item {
  + {abstract} aplicar(personagem)
}
class Arco extends Item {
  + aplicar(personagem)
}
class ItemDecorator extends Item {
  - item: Item
  ItemDecorator (item: Item)
  + aplicar(personagem)
}

ItemDecorator -o Item

ItemDecorator <|-- Laser 
ItemDecorator <|-- Faca 

@enduml