@startuml
class Personagem {
  -List<Item> itens
  +equipar(item)
}
class Item {
  -int dano
  -int tamanho
  +aplicar(personagem)
}
class Arco extends Item {
}
class Laser extends Item {
}
class Faca extends Item {
}
class ArcoComFaca extends Arco, Faca  {
}
class ArcoComLaser extends Arco, Laser  {
}
class FacaComLaser extends Faca, Laser  {
}
class FacaComLaserComArco extends Faca, Laser,Arco  {
}

Personagem "1" -> "*" Item 
FacaComLaser --[hidden] FacaComLaserComArco
@enduml